name: Onyx
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3658994196448475
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fef4f5'
    - '#302e3c'
    - '#d5c2bc'
    - '#948484'
  brandStrength: 1
  lightness: 0.8514967525843531
  saturation: 1
  rhythmicContrast: 1
purpose: []
