name: Onyx
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3658994196448475
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040507'
    - '#e6dedc'
    - '#bb7b57'
    - '#52311e'
    - '#bcb89e'
  brandStrength: 0.9477371196262538
  lightness: 0.8514967525843531
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
